Use latest unleash sdk
AppsFlyer/unleash-client-clojure pull request #17
Opened 2022-01-06 16:46 UTC by vincentjames501

We just started exploring feature flags and came across unleash and this library. I started writing my own wrapper and I realized you already have a great one! It seems like their docs have recently been updated to use `io.getunleash/unleash-client-java` instead so I'm sending this PR. Not sure if this warrants a major version bump or not. I tweaked the `:imports` from vectors to lists per https://stuartsierra.com/2016/clojure-how-to-ns.html#vectors-or-lists-1 . If you'd prefer to keep the vector styling let me know and I can change them back. Cheers!

2022-01-18 06:40 UTC, barkanido commented
@vincentjames501 hey and thanks!
sorry for the late response, I somehow missed it. I will review this. let's keep the `:imports` as is, just for the sake of not polluting `git-blame` later.

2022-01-18 06:44 UTC, barkanido requested changes
also, please revert the `:import` parens back to square brackets.

2022-01-18 06:44 UTC, barkanido commented on project.clj
> -  :dependencies [[no.finn.unleash/unleash-client-java "4.4.1"]]
can you change the project version to `"0.5.0-SNAPSHOT"`?

2022-01-18 16:19 UTC, vincentjames501 commented
I ended up doing a slightly more "clojure-y" approach instead. It's basically the same thing but it's just maps in and maps out. This is a little tailored for our companies use case but the gist is here.

```clojure
(ns singlewire-commons.micro.features
  (:require [clojure.core.cache :as cache])
  (:import (io.getunleash.strategy Strategy)
           (io.getunleash DefaultUnleash UnleashContext MoreOperations Variant FakeUnleash Unleash UnleashContext$Builder UnleashException FeatureToggle ActivationStrategy Constraint EvaluatedToggle CustomHttpHeadersProvider UnleashContextProvider)
           (java.util.function BiFunction)
           (java.util Optional)
           (io.getunleash.util UnleashConfig UnleashConfig$Builder)
           (java.net InetAddress URI Proxy)
           (io.getunleash.repository ToggleCollection FeatureToggleResponse ToggleBootstrapProvider)
           (io.getunleash.metric ClientRegistration ClientMetrics)
           (io.getunleash.event ToggleEvaluated UnleashReady UnleashEvent UnleashSubscriber)
           (io.getunleash.variant Payload VariantDefinition)))

;; Utils

(deftype BiFunctionWrapper [f]
  BiFunction
  (apply [_ toggle-name context]
    (f toggle-name context)))

;; Payload

(defn ^Payload make-payload
  [{:keys [type value]}]
  (Payload. type value))

(defn ^Payload ->payload
  [map-or-string-or-payload]
  (cond
    (instance? Payload map-or-string-or-payload) map-or-string-or-payload
    (string? map-or-string-or-payload) (make-payload {:type "string" :value map-or-string-or-payload})
    :else (make-payload map-or-string-or-payload)))

(defn payload->map
  [^Payload payload]
  (when payload
    {:type  (.getType payload)
     :value (.getValue payload)}))

;; Variant

(defn ^Variant make-variant
  [{:keys [name payload enabled? stickiness]}]
  (Variant. ^String name ^Payload (->payload payload) ^boolean enabled? ^String stickiness))

(defn ^Variant ->variant
  [map-or-variant]
  (if (instance? Variant map-or-variant)
    map-or-variant
    (make-variant map-or-variant)))

(defn variant->map
  [^Variant variant]
  (when variant
    {:enabled?   (.isEnabled variant)
     :name       (.getName variant)
     :payload    (payload->map (.orElse (.getPayload variant) nil))
     :stickiness (.getStickiness variant)}))

;; Variant Definition

(defn variant-definition->map
  [^VariantDefinition variant-definition]
  (when variant-definition
    {:name       (.getName variant-definition)
     :weight     (.getWeight variant-definition)
     :payload    (payload->map (.getPayload variant-definition))
     :stickiness (.getStickiness variant-definition)}))

;; Constraint

(defn constraint->map
  [^Constraint constraint]
  (when constraint
    {:context-name (.getContextName constraint)
     :operator     (str (.getOperator constraint))
     :values       (vec (.getValues constraint))}))

;; Context

(defn ^UnleashContext make-context
  [{:keys [app-name
           environment
           user-id
           session-id
           remote-address
           properties]}]
  (-> (cond-> (UnleashContext/builder)
              app-name (.appName app-name)
              environment (.environment environment)
              user-id (.userId user-id)
              session-id (.sessionId session-id)
              remote-address (.remoteAddress remote-address)
              properties ^UnleashContext$Builder ((fn [^UnleashContext$Builder builder]
                                                    (reduce (fn [^UnleashContext$Builder b [k v]]
                                                              (.addProperty b (name k) ^String v))
                                                            builder
                                                            properties))))
      (.build)))

(defn ^UnleashContext ->context
  [map-or-context]
  (if (instance? UnleashContext map-or-context)
    map-or-context
    (make-context map-or-context)))

(defn context->map
  [^UnleashContext context]
  (when context
    {:app-name       (.orElse (.getAppName context) nil)
     :environment    (.orElse (.getEnvironment context) nil)
     :user-id        (.orElse (.getUserId context) nil)
     :session-id     (.orElse (.getSessionId context) nil)
     :remote-address (.orElse (.getRemoteAddress context) nil)
     :properties     (reduce-kv (fn [acc k v]
                                  (assoc acc (keyword k) v))
                                {}
                                (into {} (.getProperties context)))}))

;; Strategy

(defn make-strategy
  [{:keys [name is-enabled format-params-fn]
    :or   {format-params-fn identity}}]
  (let [format-params-cache (atom (cache/lru-cache-factory {}))]
    (letfn [(format-params [params]
              (format-params-fn
                (reduce-kv (fn [acc k v]
                             (assoc acc (keyword k) v))
                           {}
                           (into {} params))))
            (format-params-memo [params]
              (when params
                (or (cache/lookup @format-params-cache params)
                    (-> (swap! format-params-cache cache/through-cache params format-params)
                        (cache/lookup params)))))]
      (reify Strategy
        (getName [_]
          name)
        (isEnabled [_ params]
          (is-enabled {:parameters (format-params-memo params)}))
        (isEnabled [_ params context]
          (is-enabled {:parameters (format-params-memo params)
                       :context    (context->map context)}))
        (isEnabled [_ params context constraints]
          (is-enabled {:parameters  (format-params-memo params)
                       :context     (context->map context)
                       :constraints (mapv constraint->map constraints)}))))))

(defn strategy->map
  [^ActivationStrategy strategy]
  (when strategy
    {:name        (.getName strategy)
     :parameters  (reduce-kv (fn [acc k v]
                               (assoc acc (keyword k) v))
                             {}
                             (into {} (.getParameters strategy)))
     :constraints (mapv constraint->map (.getConstraints strategy))}))

;; Feature Toggle

(defn feature-toggle->map
  [^FeatureToggle feature-toggle]
  (when feature-toggle
    {:name       (.getName feature-toggle)
     :enabled?   (.isEnabled feature-toggle)
     :strategies (mapv strategy->map (.getStrategies feature-toggle))
     :variants   (mapv variant-definition->map (.getVariants feature-toggle))}))

;; Evaluated Toggle

(defn evaluated-toggle->map
  [^EvaluatedToggle evaluated-toggle]
  (when evaluated-toggle
    {:name     (.getName evaluated-toggle)
     :enabled? (.isEnabled evaluated-toggle)
     :variant  (variant->map (.getVariant evaluated-toggle))}))

;; Subscriber

(deftype Subscriber [on-error
                     on-event
                     on-ready
                     toggle-evaluated
                     toggles-fetched
                     client-metrics
                     client-registered
                     toggles-backed-up
                     toggle-backup-restored]
  UnleashSubscriber
  (^void onError [_ ^UnleashException ex]
    (on-error ex))
  (^void on [_ ^UnleashEvent event]
    (on-event event))
  (^void onReady [_ ^UnleashReady ready]
    (on-ready ready))
  (^void toggleEvaluated [_ ^ToggleEvaluated evaluated]
    (toggle-evaluated evaluated))
  (^void togglesFetched [_ ^FeatureToggleResponse response]
    (toggles-fetched response))
  (^void clientMetrics [_ ^ClientMetrics metrics]
    (client-metrics metrics))
  (^void clientRegistered [_ ^ClientRegistration registration]
    (client-registered registration))
  (^void togglesBackedUp [_ ^ToggleCollection _collection]
    (toggles-backed-up))
  (^void toggleBackupRestored [_ ^ToggleCollection collection]
    (toggle-backup-restored collection)))

(defn- no-op [_])

(defn ^UnleashSubscriber make-subscriber
  "Expects a map of event types to event handlers."
  [{:keys [on-error on-event  [...]

2022-01-19 07:23 UTC, asafch commented
@vincentjames501 

1. I'm not sure why you added the code snippet for `singlewire-commons.micro.features`?
2. And what is your company's use case for which you geared your code towards?.
3. In this PR's opening comment could you please add a link to the `unleash-client-java` release which changed the artifact coordinates in Maven Central?
4. Building on @barkanido 's comment above, if `unleash-client-java:5.0.X` introduced breaking changes, we need to see if using that also causes breakages in `unleash-client-clojure`. If we decide to go ahead with them then we would need to bump this library's major version rather than minor version.

2022-01-19 16:54 UTC, vincentjames501 commented
@asafch , the code snippet is just an alternate approach for this library to consider. Feel free to ignore it. The idea is just that everything is configured via maps and the output is maps vs just doing a java builder pattern in clojure. 

Example in this library:
```clojure
Variant support
(require '[unleash-client-clojure.variant :as v])
(u/get-variant unleash "DemoVariantWithPayload")
(let [x (u/get-variant unleash "DemoVariantWithPayload")]
  [(v/get-name x)
   (v/get-type x)
   (v/variant-enabled? x)
   (v/get-value x)])
Advanced client config
;; the builder namespace supports passing builder confgurations as functions
(require '[unleash-client-clojure.builder :as b])
(def unleash (u/build
               (b/app-name "app-name")
               (b/unleash-api "http://unleash.herokuapp.com/api/")
               (b/environment "staging")
               (b/fetch-toggles-interval 1)))
```

Would basically become something like:
```clojure
(make-unleash {:api-url "http://localhost:4242/api"
                            :api-key "*:development.d6f9639e9c0a65ed5308a337bf934df89410d095140ea4561b4b52c9"
                            :app-name "test"})
```

```clojure
(get-variant-with-context c "Foo.Bar" {:user-id "abc123"})
=> {:enabled? true, :name "Myname", :payload {:type "string", :value "my-value"}, :stickiness "default"}
```

Then you can just use clojure primitives to get the keys/values you care about. Constantly converting a map to a `context` object w/ builder functions is a bit awkward for us. Anyways, folks can ignore that comment but it's how I'd personally want to consume a Clojure API so I'll be dropping this PR. Feel free to use any part of this you'd like.

2022-01-19 16:54 UTC, closed without merging

2022-01-19 17:52 UTC, barkanido commented
Thanks @vincentjames501 . Just to clarify, the idea was to do an un-opinionated , bare minimal clojure wrapper that would merely hide all the java interop from the client code. Users can then use this (with a minimal price paid ) in order to have their own cozy API or DSL or what have you.

It has its own pros like minimal maintenance and cons like being a bit Java-leaky as you mentioned.